# Generated by Django 4.0.5 on 2022-07-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_first_name', models.CharField(max_length=100, null=True)),
                ('sender_last_name', models.CharField(max_length=100, null=True)),
                ('sender_email_address', models.CharField(max_length=100, null=True)),
                ('sender_phone_number', models.CharField(max_length=11, null=True)),
                ('inquiry_description', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email_address', models.CharField(max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment_scheduler.user')),
                ('is_available', models.BooleanField(null=True)),
            ],
            bases=('appointment_scheduler.user',),
        ),
        migrations.CreateModel(
            name='AvailabilityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_from', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('availability_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='appointment_scheduler.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_scheduler.availabilitytime')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_assigned_by', to='appointment_scheduler.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointment_scheduler.employee')),
            ],
        ),
    ]
