import type { NextPage } from "next";
import Head from "next/Head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Animate from '../components/project/layouts/Animate'

import { Box, Flex, HStack, Text } from "@chakra-ui/react";
import ContactForm from '../components/modules/forms/ContactForm'

const Home: NextPage = () => {
  return (
    <Animate>
      <Head>
        <title>Zouk Studios - Hire a Designer Today!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/zouk_studios_icon_alt.ico" />
      </Head>
      <HStack spacing='10em'>
        <Box alignSelf='center'>
          <Text fontSize='lg' width='500px' lineHeight={7} fontWeight='medium' color='orange.200'>
            Complex Website Design, Simplified.
          </Text>
          <Text fontSize='5xl' fontWeight='extrabold' color='white'>
            Let's grow, together.
          </Text>
          <Text width='450px' mt={7} lineHeight={7} color='white' fontSize='lg'>
            Website design can be difficult. Zouk Studios is here to help. Find a team of creative designers today to help you develop a unique face for your storefront.
          </Text>
        </Box>
        <Box width='50%' ml={10}>
          <Text lineHeight={9} fontSize='3xl' fontWeight='bold' color='white' mb={26}>Get Started</Text>
          <ContactForm width='400px' />
        </Box>
      </HStack>
    </Animate>
  );
};

export default Home;
